import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import { Footer } from "./components/view/footer";
import { NavMenu, BookMenu } from "./components/nav_bookmenu";
import { Nav } from "./components/view/nav";
import { SmoothScrollbar } from "./components/smoothscrollbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScrollbar>
          <StyledComponentsRegistry>
            <Nav />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </SmoothScrollbar>
      </body>
    </html>
  );
}
